#!/usr/bin/env python
"""Released under the MIT License
Copyright 2015, 2016 MrTijn/Tijndagamer
"""
from mpu6050 import mpu6050
from time import sleep
import os
import csv
#import smbus2


sensor = mpu6050(0x68)

while True:
    accel_data = sensor.get_accel_data()
    gyro_data = sensor.get_gyro_data()
    temp = sensor.get_temp()

    print("Accelerometer data")
    print("x: " + str(accel_data['x']))
    print("y: " + str(accel_data['y']))
    print("z: " + str(accel_data['z']))

    print("Gyroscope data")
    print("x: " + str(gyro_data['x']))
    print("y: " + str(gyro_data['y']))
    print("z: " + str(gyro_data['z']))

    print("Temp: " + str(temp) + " C")

    file_path = "sensor_data.csv"
    file_exists = os.path.exists(file_path)

    with open(file_path, "a", newline='') as file:
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(["Accelerometer x", "Accelerometer y", "Accelerometer z", 
                             "Gyroscope x", "Gyroscope y", "Gyroscope z", "Temperature"])

        writer.writerow([accel_data['x'], accel_data['y'], accel_data['z'], 
                         gyro_data['x'], gyro_data['y'], gyro_data['z'], temp])
    sleep(0.5)
